on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - id: tag
        uses: Viostream/github-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: rohith/publish-nuget@v2
        with:
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          PROJECT_FILE_PATH: DbUp.Snowflake.csproj
          PACKAGE_NAME: DbUp.Snowflake
          TAG_COMMIT: false
          VERSION_STATIC: ${{ steps.tag.outputs.new_tag }}
